[language-server.rust-analyzer.config]
check = { command = "clippy", features = "all" }
checkOnSave = { command = "clippy" }
diagnostics = { experimental = { enable = true } }
hover = { actions = { enable = true } }
typing = { autoClosingAngleBrackets = { enable = true } }
cargo = { allFeatures = true }
procMacro = { enable = true }


[language-server.taplo.config]
root_dir = [".git", "*.toml"]

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
auto-format = true
